### PR TITLE
Optimize adjacent itertool

### PR DESCRIPTION
**Pull request by james-wasson**
### Issue reference
more-itertools/more-itertools#811

### Changes
Increases the performance of the adjacent itertool by using a counting method to check for adjacency.

Check the issue for performance overview.

### CODE REVIEW

**Comment by bbayles** [comment]
I think I'm -1 on this: the performance does indeed look better, but the code is simpler before.

I would be open to changing `windowed` to `sliding_window`, which I think is a simpler/faster implementation; `adjacent` doesn't need the additional features.

**Comment by james-wasson** [comment]
@bbayles I would assume the counting approach would always be a better option but maybe this is a sub optimal way of implementing it. I will try to improve it and if I can't I will change the PR to use `sliding_window` instead.

**Comment by james-wasson** [comment]
@bbayles I tried just adding the `sliding_window` replacement and for my tests didn't come up with any major results. After trying around a little more I was able to remove the `accumulate`  dependency, increase readability, and add a slight performance increase.

I think this is as far as I can take this function so I would love to hear any feedback.

Thanks!

**Comment by james-wasson** [comment]
@bbayles I have compacted this further and increased readability; I don't think this can go much smaller or faster.
If you're still at a -1 on this PR feel free to close it, no worries :)

**Comment by james-wasson** [comment]
If needed in the future my recommendation is to go with @pochmann approach here: https://github.com/more-itertools/more-itertools/issues/811#issuecomment-2002209995

Closing this PR now. See the issue for resolution.

**Pull request closed without merging**
