### PR TITLE
Add interleave_evenly function and tests

### PR DESCRIPTION
**Pull request by mbugert**
### Issue reference

more-itertools/more-itertools#530

### Changes
Add `interleave_evenly` implementation plus unit tests.

For some unknown reason, the newly added tests all failed with `AttributeError: module 'more_itertools' has no attribute 'interleave_evenly'` in my pycharm, but when I moved the `InterleaveEvenlyTests` class into a separate file, it worked.

### CODE REVIEW

**Comment by FinalSh4re** [comment]
You didn't add your function to \_\_all\_\_, this should be the reason why the method isn't found.

https://github.com/more-itertools/more-itertools/blob/7b89d6ead4725fa1160e466ab1ebb55747de55aa/more_itertools/more.py#L38

**Comment by mbugert** [comment]
Right, thanks for pointing out. I've added it and also updated `api.rst`.

**Comment by bbayles** [comment]
One question before I merge this: is there any reason not to compute the lengths for the user, rather than making them pass them in? None of the tests use custom lengths.

**Comment by mbugert** [comment]
Good question.
The idea was to make it compatible with any iterable: in my original use case, I interleaved iterators which were `itertools.combinations`, i.e. iterators which produce a known number of items but are too expensive to keep in memory as lists. I agree that it's ugly with plain lists though.

I can change it so that iterable lengths are inferred automatically (with `len()` on those iterables which support it), making `lengths` an optional kwarg.

**Comment by mbugert** [comment]
Looks much cleaner now. WDYT?

**Comment by bbayles** [comment]
Thanks!

**Pull request merged**
