### PR TITLE
repeat_each itertool

### PR DESCRIPTION
**Pull request by FinalSh4re**
### Issue reference
#532 
I decided to combine both functions from the issue, since the `repeat_incrementally()` function also covers the `repeat_each()` one's functionality by setting the step size to 0. However, since I believe having constant repeats is more commonly used I set the incremental step default to 0 (constant repeating of each element).

### Changes
Adding `repeat_each` itertool.

This is my first PR, please let me know if anything is missing or needs to be changed. I tried to mimic previous PRs made by other people, but I might have missed something. Especially the stub file I'm not sure about. Thanks!

### CODE REVIEW

**Comment by bbayles** [comment]
Oh, I should have specified: I like this without the `step` argument. If you can drop back to the simpler version, I'd be happy to merge that.

**Review by bbayles — CHANGES_REQUESTED** [review]
* See the comment about about the `step` argument
* Please do fix the failing tests

**Comment by FinalSh4re** [comment]
I changed it back to the initial version from the issue. As for the failing tests, how do I add the missing dependencies it's asking for? Sorry, I'm completely new to this.

**Comment by bbayles** [comment]
The issue is this:

``
would reformat more_itertools/more.pyi
would reformat more_itertools/more.py
Oh no! 💥 💔 💥
2 files would be reformatted, 9 files would be left unchanged.
```

You should be able to fix by installing `black` (`pip install black`) and then running it (`black .`).

**Comment by bbayles** [comment]
OK, last requests: could you write tests for what you expect to happen for (a) empty iterator, (b) repeat set to 0?

**Review by bbayles — APPROVED** [review]

**Comment by FinalSh4re** [comment]
Thanks for the patience and the help. 

One more thing, I just noticed that there is a massive problem with my implementation. For infinite iterators the method will break, since `*map()` unpacks the resulting iterator before passing it to `chain()`.

Eg. 

    repeat_each(count(), 3)

would crash the program.  

I think a better alternative would be using `chain.from_iterable()`:

    def repeat_each(iterable, n=2):
        return chain.from_iterable(map(repeat, iterable, repeat(n)))

This should (1) fix the problem with infinite iterators and (2) reduce memory usage in general since the map iterator doesn't get unpacked but consumed lazily instead. What do you think?

**Comment by bbayles** [comment]
I'll take a PR with the fix and a test demonstrating the behavior is better. Thanks!

**Comment by sassbalint** [comment]
@FinalSh4re This PR helped me a lot in creating my own first PR. #542 Thanks! :)

**Pull request merged**
