### PR TITLE
Implement zip_broadcast

### PR DESCRIPTION
**Pull request by bbayles**
Re: https://github.com/more-itertools/more-itertools/issues/543, this PR adds `zip_broadcast`. See the issue for discussion.

### CODE REVIEW

**Comment by bbayles** [comment]
Tests for 3.10 are failing due to https://github.com/python/typing/issues/865.

**Comment by kalekundert** [comment]
Thanks for implementing this; it does do what I want.  I have a few comments, though:

1. The function returns the wrong value when `*objects` is empty.  It yields a single empty tuple, when it should yield nothing.
2. I think `zip_fill()` is a better name than `zip_broadcast()`.  The reason is that the ability to support 2- and 3-dimensional inputs is a big part of what `np.broadcast()` is used for, while this is function is specifically for 1-dimensional inputs.
3. Both this function and `always_iterable()` have the same test to see if an object is iterable.  Would it make sense to factor this into it's own publicly-available function?

Here are the tests I wrote for my implementation.  I have some test cases that you don't, so you might want to include them:
```
@pytest.mark.parametrize(
        "objs, kwargs, expected", [(
            # 0 items
            [],
            {},
            [],
        ), (
            [[]],
            {},
            [],
        ), (
            # 1 item
            [1],
            {},
            [(1,)],
        ), (
            [[1]],
            {},
            [(1,)],
        ), (
            [[1], 2],
            {},
            [(1, 2)],
        ), (
            [1, [2]],
            {},
            [(1, 2)],
        ), (
            [[1], [2]],
            {},
            [(1, 2)],
        ), (
            # 2 items
            [[1, 2]],
            {},
            [(1,), (2,)],
        ), (
            [[1, 2], 3],
            {},
            [(1, 3), (2, 3)],
        ), (
            [1, [2, 3]],
            {},
            [(1, 2), (1, 3)],
        ), (
            [[1, 2], [3, 4]],
            {},
            [(1, 3), (2, 4)],
        ), (
            # not iterable
            ['ab'],
            {},
            [('ab',)],
        ), (
            ['ab'],
            dict(not_iterable=None),
            [('a',), ('b',)],
        ), (
            [[1, 2]],
            dict(not_iterable=list),
            [([1, 2],)],
        ), (
            # unequal length
            [[], [1]],
            {},
            [],
        ), (
            [[1], [2, 3]],
            {},
            [(1, 2)],
        ), (
            # infinite
            [1, repeat(2), [3]],
            {},
            [(1, 2, 3)],
        )],
)
def test_zip_with_scalars(objs, kwargs, expected):
    assert list(zip_with_scalars(*objs, **kwargs)) == expected

@pytest.mark.parametrize(
        "objs, kwargs, error", [(
            # 0 items
            [[], [1]],
            dict(strict=True),
            UnequalIterablesError,
        ), (
            [[1], [2, 3]],
            dict(strict=True),
            UnequalIterablesError,
        )],
)
def test_zip_with_scalars_err(objs, kwargs, error):
    with pytest.raises(error):
        list(zip_with_scalars(*objs, **kwargs))
```

**Comment by kalekundert** [comment]
`zip_repeat()` might be another reasonable name.

**Comment by bbayles** [comment]
Thanks for the review. I'm going to go with the `zip_broadcast` name. I considered doing an `_is_iterable` function, but I'll wait for a third consumre of it. Your point about the empty input was right on.

**Pull request merged**
