### PR TITLE
Added takewhile_inclusive

### PR DESCRIPTION
**Pull request by OlegAlexander**
### Issue reference

https://github.com/more-itertools/more-itertools/issues/730

### Changes

I've added the `takewhile_inclusive` function and tests for it. 

I ran the entire test suite and all the tests passed except for one:

```console
======================================================================
FAIL: test_zero_limit (tests.test_more.TimeLimitedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\github\more-itertools\tests\test_more.py", line 3919, in test_zero_limit
    self.assertEqual(actual, expected)
AssertionError: Lists differ: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,[760707 chars]8982] != []

First list contains 108983 additional elements.
First extra element 0:
0
```

I wasn't sure how to fix it so I left it alone. I'm on Windows 11. Python 3.10.6.

Please let me know if you'd like me to make any changes. Thank you!

### CODE REVIEW

**Comment by bbayles** [comment]
Could you fix this `flake8` error?

> ./tests/test_more.py:5432:80: E501 line too long (81 > 79 characters)

Thanks for the PR!

**Comment by OlegAlexander** [comment]
Done.

**Comment by OlegAlexander** [comment]
Trying again with: 

```console
python -m black more_itertools/more.pyi -t py37 --line-length=79 -S
python -m black tests/test_more.py -t py37 --line-length=79 -S
```

Fingers crossed.

**Review by bbayles — APPROVED** [review]

**Comment by bbayles** [comment]
Many thanks!

**Pull request merged**
