### PR TITLE
Optimize windowed itertool

### PR DESCRIPTION
**Pull request by james-wasson**
### Issue reference
more-itertools/more-itertools#809

### Changes
I have been working towards increasing the performance of the windowed method and have made some good headway. Main performance gains come from using built in itertools methods and using `islice` to "fast forward" the windows.

### CODE REVIEW

**Comment by bbayles** [comment]
I'm -0 on this one - the better performance for larger size inputs is good, but I'm not sure if the extra complexity is worth it.

**Comment by james-wasson** [comment]
I can test out the performance of the single non-overlapping branch but I really do think non initializing a deque if possible is the way to go here. I will see if I can optimize further.

**Comment by james-wasson** [comment]
Newest changes improve every metric minorly anywhere from 0-40% speed up over base code. Not huge but considering this is one of the most widely used methods and is used all over this code base as well it should provide a nice bonus.

**Comment by bbayles** [comment]
Thanks for the analysis. I'll take this PR if you can revert the change to the argument names?

**Comment by james-wasson** [comment]
@bbayles Done, I will avoid changing argument names in the future. Thanks!

**Review by bbayles — APPROVED** [review]

**Pull request merged**
