### PR TITLE
interleave_longest refactored

### PR DESCRIPTION
**Pull request by SergBobrovsky**

### CODE REVIEW

**Comment by SergBobrovsky** [comment]
[demo.py.txt](https://github.com/more-itertools/more-itertools/files/4306485/demo.py.txt)

**Comment by bbayles** [comment]
FYI, improving `interleave_longest` and `roundrobin` has been studied before - see [issue 189](https://github.com/more-itertools/more-itertools/pull/189#issuecomment-355298498). Your implementation matches up with `interleave_longest_queue_append` from that issue.

As that issue mentions, CPython and PyPy have exhibit different performance. Also, performance is sensitive to the number and composition of the iterables. As far as I can tell, there isn't an implementation that is better across the board.

Some test code is below, here is a sample run with 1000 iterables of varying lengths:

Function | Cpython 3.7.3 | PyPy 7.2.0
-- | -- | --
interleave_longest_filter_partial | 6.94 | 43.36
interleave_longest_queue_append | 5.64 | 9.20
interleave_longest_queue_rotate | 6.58 | 10.44
interleave_longest_loop | 5.67 | 9.08
interleave_longest_comprehension | 3.35 | 9.85


---

<details><summary>Test code</summary>

```python
from collections import deque
from functools import partial
from itertools import chain, zip_longest
from operator import is_not
from timeit import timeit

from more_itertools import consume


def interleave_longest_filter_partial(*iterables, _marker=object()):
    func = partial(is_not, _marker)
    it = chain.from_iterable(zip_longest(*iterables, fillvalue=_marker))
    return filter(func, it)


def interleave_longest_queue_append(*iterables):
    next_methods = (iter(it).__next__ for it in iterables)
    q = deque(next_methods)
    popleft = q.popleft
    append = q.append

    while q:
        next_method = popleft()
        try:
            yield next_method()
        except StopIteration:
            pass
        else:
            append(next_method)


def interleave_longest_queue_rotate(*iterables):
    next_methods = (iter(it).__next__ for it in iterables)
    q = deque(next_methods)
    rotate = q.rotate
    popleft = q.popleft

    while q:
        try:
            while True:
                yield q[0]()
                rotate(-1)
        except StopIteration:
            popleft()


def interleave_longest_loop(*iterables):
    next_methods = [iter(it).__next__ for it in iterables]

    n = len(iterables)
    indexes = list(range(n))
    finished = [False] * n
    while n:
        for i in indexes:
            if finished[i]:
                continue
            try:
                yield next_methods[i]()
            except StopIteration:
                n -= 1
                finished[i] = True


def interleave_longest_comprehension(*iterables, _marker=object()):
    it = chain.from_iterable(zip_longest(*iterables, fillvalue=_marker))
    return (x for x in it if x is not _marker)


for func in (
    interleave_longest_filter_partial,
    interleave_longest_queue_append,
    interleave_longest_queue_rotate,
    interleave_longest_loop,
    interleave_longest_comprehension,
):
    iterables = [list(range(1, 10 * n + 1)) for n in range(1000)]
    def stmt():
        it = func(*iterables)
        consume(it)
    name = func.__name__
    result = timeit(stmt, number=10)
    print(name, result, sep='\t')
```

</details>

**Comment by SergBobrovsky** [comment]
Nice investigation!
I slightly expanded tests (very slightly) and append new realization.
Isn't interleave_longest_list new king of mountain?

ps. How to insert colored code here?

```cpython 3.7.5
                       1000 datasets                        
interleave_longest_filter_partial  	9.893267
interleave_longest_queue_append    	8.916891
interleave_longest_queue_rotate    	9.776474
interleave_longest_loop            	9.570591
interleave_longest_list            	6.110740
interleave_longest_comprehension   	5.882333
                        10 datasets                         
interleave_longest_filter_partial  	6.629330
interleave_longest_queue_append    	5.293881
interleave_longest_queue_rotate    	5.873099
interleave_longest_loop            	5.800743
interleave_longest_list            	2.600764
interleave_longest_comprehension   	3.455919

pypy3 7.3.0
                       1000 datasets                        
interleave_longest_filter_partial  	40.095075
interleave_longest_queue_append    	10.897430
interleave_longest_queue_rotate    	11.857380
interleave_longest_loop            	10.939408
interleave_longest_list            	10.095948
interleave_longest_comprehension   	10.723662
                        10 datasets                         
interleave_longest_filter_partial  	37.018332
interleave_longest_queue_append    	9.025303
interleave_longest_queue_rotate    	9.893190
interleave_longest_loop            	9.511210
interleave_longest_list            	8.383689
interleave_longest_comprehension   	11.436751```


Test code:
```
from collections import deque
from functools import partial
from itertools import chain, zip_longest, cycle
from operator import is_not
from timeit import timeit


def consume(iterator):
    deque(iterator, maxlen=0)


def interleave_longest_filter_partial(*iterables, _marker=object()):
    func = partial(is_not, _marker)
    it = chain.from_iterable(zip_longest(*iterables, fillvalue=_marker))
    return filter(func, it)


def interleave_longest_queue_append(*iterables):
    next_methods = (iter(it).__next__ for it in iterables)
    q = deque(next_methods)
    popleft = q.popleft
    append = q.append

    while q:
        next_method = popleft()
        try:
            yield next_method()
        except StopIteration:
            pass
        else:
            append(next_method)


def interleave_longest_queue_rotate(*iterables):
    next_methods = (iter(it).__next__ for it in iterables)
    q = deque(next_methods)
    rotate = q.rotate
    popleft = q.popleft

    while q:
        try:
            while True:
                yield q[0]()
                rotate(-1)
        except StopIteration:
            popleft()


def interleave_longest_loop(*iterables):
    next_methods = [iter(it).__next__ for it in iterables]

    n = len(iterables)
    indexes = list(range(n))
    finished = [False] * n
    while n:
        for i in indexes:
            if finished[i]:
                continue
            try:
                yield next_methods[i]()
            except StopIteration:
                n -= 1
                finished[i] = True


def interleave_longest_list(*iterables):
    pool = [iter(it).__next__ for it in iterables]
    while pool:
        try:
            for nxt in cycle(pool):
                yield nxt()
        except StopIteration:
            pool.remove(nxt)


def interleave_longest_comprehension(*iterables, _marker=object()):
    it = chain.from_iterable(zip_longest(*iterables, fillvalue=_marker))
    return (x for x in it if x is not _marker)


for iterables in ([list(range(1, 10 * n + 1)) for n in range(1000)],
                  [list(range(1, 100000 * n + 1)) for n in range(10)]):
    print(f'{len(iterables)} datasets'.center(60))
    for func in (
            interleave_longest_filter_partial,
            interleave_longest_queue_append,
            interleave_longest_queue_rotate,
            interleave_longest_loop,
            interleave_longest_list,
            interleave_longest_comprehension,
    ):
        def stmt():
            it = func(*iterables)
            consume(it)


        name = func.__name__
        result = timeit(stmt, number=10)
        print(f'{name:35}\t{result:f}')
```

**Comment by bbayles** [comment]
`interleave_longest_list` looks like a small improvement, but I don't think it's enough for me to switch the implementation again.

Do this for code formatting:

```
```python
```

`interleave_longest_list` looks like a small improvement, but I don't think it's enough for me to switch the implementation again. If someone comes up with a method that is an order of magnitude better, I'll happily change it though!

**Comment by pochmann3** [comment]
Just in case someone else ever digs this out as well:

`interleave_longest_list` is wrong. For example, `print(*interleave_longest_list([1, 3], [], [2]))` prints `1 3 2` instead of `1 2 3`.

And I'm not sure `pool.remove(nxt)` is a good idea, could be slow if `nxt` is at the end of the list, and might remove the wrong one if there are two equal ones.

**Pull request closed without merging**
